# Generated by Django 5.0.14 on 2025-05-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('is_malicious', models.BooleanField()),
                ('abuse_confidence_score', models.IntegerField()),
                ('country_code', models.CharField(blank=True, max_length=5, null=True)),
                ('isp', models.CharField(blank=True, max_length=255, null=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('hostnames', models.TextField(blank=True, null=True)),
                ('usage_type', models.CharField(blank=True, max_length=255, null=True)),
                ('total_reports', models.IntegerField(blank=True, null=True)),
                ('distinct_users', models.IntegerField(blank=True, null=True)),
                ('last_reported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
