# Generated by Django 5.0.14 on 2025-05-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipaddress',
            old_name='domain',
            new_name='as_domain',
        ),
        migrations.RenameField(
            model_name='ipaddress',
            old_name='isp',
            new_name='as_name',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='abuse_confidence_score',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='distinct_users',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='hostnames',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='is_malicious',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='last_reported_at',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='total_reports',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='usage_type',
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='asn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='attack_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='continent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='continent_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
