# Generated by Django 5.0.14 on 2025-05-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_domain_ipaddress_as_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterUniqueTogether(
            name='ipaddress',
            unique_together={('ip_address', 'attack_label')},
        ),
    ]
